version: '3.7'
services:
  mongodb_container:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017


nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./uploads:/usr/share/nginx/html/uploads
      - ./nginx.conf:/etc/nginx/nginx.conf